# Generated by Django 3.2.5 on 2021-12-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_level', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'SSCE'), (1, 'Jss3'), (2, 'Skill Worker'), (3, 'BSc'), (4, 'Illiterate'), (5, 'P/G')])),
                ('gender', models.PositiveIntegerField(choices=[('', 'Select'), (1, 'Male'), (0, 'Female')])),
                ('source_of_income', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Employee'), (1, 'Skill-Worker'), (2, 'Daily-Worker'), (3, 'Agriculture'), (4, 'Has no work')])),
                ('do_you_avoid_any_kind_of_food', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Yes'), (1, 'No')])),
                ('do_you_have_a_meal_time_table', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Yes'), (1, 'No')])),
                ('vegetables', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('red_meat', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('chicken', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('fish', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('milk', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('dairy_product', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('egg', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('bread', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('legumes', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('fruits', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('tea', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('coffee', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('fresh_juice', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('soft_juice', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('eba', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('fufu', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('yam', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('rice', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('beans', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('elubo', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('maize', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('garri', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('pounded_yam', models.PositiveIntegerField(choices=[('', 'Select'), (0, '≥ 1 per week'), (1, '≤ 1 per week'), (2, 'Never taken')])),
                ('monday_BF', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('monday_LH', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('monday_DN', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('tuesday_BF', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('tuesday_LH', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('tuesday_DN', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('wednesday_BF', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('wednesday_LH', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('wednesday_DN', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('thursday_BF', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('thursday_LH', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('thursday_DN', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('friday_BF', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('friday_LH', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('friday_DN', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('saturday_BF', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('saturday_LH', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('saturday_DN', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('sunday_BF', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('sunday_LH', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
                ('sunday_DN', models.PositiveIntegerField(choices=[('', 'Select'), (0, 'Carbohydrate'), (1, 'Legumes'), (2, 'Beverages'), (3, 'Protein'), (4, 'Fruit'), (5, 'Vegitable'), (6, 'Fat and oil'), (7, 'Nut'), (8, 'Red meat'), (9, 'White meat'), (10, 'Egg'), (11, 'Sugar'), (12, 'Diary')])),
            ],
        ),
    ]
