# Generated by Django 3.2.10 on 2021-12-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('reserv_date', models.DateField()),
                ('numb_guests', models.PositiveIntegerField()),
                ('alt_reserv_date', models.TimeField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
